# Generated by Django 3.2.7 on 2021-10-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='flight',
            new_name='flight_id',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='idUser',
            new_name='idUser_id',
        ),
    ]
