# Generated by Django 3.2.7 on 2021-10-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0002_auto_20211017_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='flight_id',
            new_name='flight',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='idUser_id',
            new_name='idUser',
        ),
    ]
