# Generated by Django 3.2.7 on 2021-10-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0003_auto_20211017_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.BooleanField(default=False, verbose_name='Role'),
            preserve_default=False,
        ),
    ]
