# Generated by Django 3.2.7 on 2021-10-21 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0004_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='AdminAccount',
        ),
    ]
