# Generated by Django 3.2.7 on 2021-10-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0005_auto_20211020_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='flight',
            new_name='flightNumber',
        ),
    ]
