# Generated by Django 3.2.7 on 2021-10-23 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0006_rename_flight_bookings_flightnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='flightNumber',
            new_name='flight',
        ),
    ]
