# Generated by Django 3.2.7 on 2021-10-28 21:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0009_alter_bookings_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 21, 54, 19, 699629, tzinfo=utc)),
        ),
    ]
