# Generated by Django 3.2.7 on 2021-10-31 15:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0010_auto_20211028_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 15, 45, 0, 596984, tzinfo=utc)),
        ),
    ]
